name: Build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
        # Setup key
        #  - run: set -eu
        # - run: mkdir "$HOME/.ssh"
        #  - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"

        # Build
      - name: Build
        run: npm run build

        # Deploy
       - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
        SSH_PRIVATE_KEY: git@github.com:tema2294/tema2294.github.io.git



